Pipeline should continue even on error in one source.

diff --git a/data/pipeline/pipeline b/data/pipeline/pipeline
--- a/data/pipeline/pipeline
+++ b/data/pipeline/pipeline
@@ -8,7 +8,10 @@ fi
 
 find . | grep $filter| grep run.sh | grep -v .swp | sort | while read ln; do
   echo "Processing $ln ...";
-  $ln || { echo "Failed."; exit 1; }
+  $ln || {
+    echo -e "\e[31mFailed!\e[0m"
+    # exit 1
+  }
   echo "Success."
 done;
 
